/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef search_CONSTANTS_H
#define search_CONSTANTS_H

#include "search_types.h"



class searchConstants {
 public:
  searchConstants();

};

extern const searchConstants g_search_constants;



#endif
